const S={start:'https://www.fda.gov.tw/tc/newsContent.aspx?cid=4&id=31669',aug:'https://www.fda.gov.tw/TC/newsContent.aspx?cid=4&id=t634569',tainan:'https://health.tainan.gov.tw/page.asp?mainid=2CA6162C-36F6-47B5-A2A2-E4FB28BD4DC7',pros:'https://www.tpc.moj.gov.tw/292885/293089/293092/',union:'https://www.fda.gov.tw/tc/siteList.aspx?sid=13708',unionFirst:'https://www.fda.gov.tw/tc/newsContent.aspx?cid=4&id=t634379',unionTrace:'https://www.cna.com.tw/news/ahel/202607070185.aspx',unionPenalty:'https://www.cna.com.tw/news/aloc/202607070129.aspx',unionUpdate:'https://www.fda.gov.tw/TC/newsContent.aspx?cid=4&id=t634479'};
const union=[['泰山','好理調合油 600 mL','4710095373793',['20270725']],['泰山','好理調合油 2 L','',['20270725']],['泰山','精選蔬菜油 3 L','',['20270725']],['泰山','歐式果實精華調合油 1.5 L','',['20271013']],['泰山','花生風味調和油 2 L','',['20271009','20271024','20271127']],['福壽','大豆沙拉油 600 mL','',['20270421','20270422']],['福壽','不飽和大豆沙拉油 2 L','',['20280410']],['福壽','大豆沙拉油 3 L','',['20270409','20270413','20270415','20270420','20270421']]].map(x=>({brand:x[0],name:x[1],barcode:x[2],dates:x[3],status:'yellow',note:'此商品列入食藥署公告清單，需再核對瓶身有效日期。',source:S.union}));
const camellia=[['連淨','連淨苦茶油','','red','2026/7/21 業者自主通報苯駢芘 2.9 μg/kg，超過 2.0 μg/kg 限量。',S.start],['永豐餘生技','在地金花小菓苦茶油','2028/05/25','red','自主送驗苯駢芘 2.9 μg/kg 不合格。',S.aug],['國際機能食品','台灣苦茶油 500 ml','2027/12/25','red','檢出苯駢芘 2.6 μg/kg 不合格。',S.aug],['高仰三','高仰三苦茶油','','yellow','同一製油供應鏈有不合格批次；請再核對日期／批號。',S.aug],['庭茂','庭茂苦茶油','','yellow','列入同批原料預防性下架追查範圍。',S.aug],['聚興製油工廠','東山苦茶油','','red','臺南市擴大抽驗檢出苯駢芘 2.1 μg/kg。',S.tainan],['德昌商號','苦茶油','','red','臺南市擴大抽驗檢出苯駢芘 3.0 μg/kg。',S.tainan],['宮北合作農場','苦茶油','','red','臺南市擴大抽驗檢出苯駢芘 2.5 μg/kg。',S.tainan]].map(x=>({brand:x[0],name:x[1],date:x[2],status:x[3],note:x[4],source:x[5]}));
const timeline=[['7/21','alert','自主通報','連淨苦茶油檢出苯駢芘超標','連淨晚間自主通報，產品檢出 2.9 μg/kg；法定限量為 2.0 μg/kg。這是本波事件公開起點。',S.start,'食藥署 7/22 公告'],['7/22','action','稽查・下架','食藥署、新北市衛生局進廠查核','該批共生產 5,024 罐；棉花田、統一生機等通路已有 939 罐上市。業者暫停苦茶油作業與販售，現場另抽驗 5 件。',S.start,'食藥署'],['7/23–24','action','主動擴大抽驗','臺南啟動食用油品安全擴大抽驗','抽驗 23 件油品，其中 16 件為苦茶油。此處是「監管行動」，不是新增 23 件問題商品。',S.tainan,'臺南市衛生局'],['7/29','alert','第二條事件線','永豐餘生技自主通報在地金花小菓苦茶油','產品檢出苯駢芘 2.9 μg/kg。官方追出：永豐餘向威加下單，威加委託源春製油，再由亞世家分裝、貼標。',S.aug,'食藥署 8/1 說明'],['7/31','alert','同代工廠再通報','國際機能食品自主通報台灣苦茶油','委託源春製油廠製造的 500 ml 苦茶油檢出 2.6 μg/kg；食藥署會同新北市衛生局查核。',S.aug,'食藥署'],['8/1','trace','供應鏈追查','源春同批原料涉及多項產品','食藥署公布永豐餘／威加／源春線調查；同批苦茶籽製成多項產品並預防性下架。原料苦茶籽來源當時仍缺乏明確佐證。',S.aug,'食藥署'],['8/3','alert','擴大抽驗結果','臺南 23 件抽驗中，3 件苦茶油超標','其餘 20 件符合規定。3 件分別檢出 2.5、2.1、3.0 μg/kg，並向雲林、嘉義、臺中等上游追查。',S.tainan,'臺南市衛生局'],['8/4','judicial','刑事偵查','北檢搜索 17 處，追查疑似產地混充','北檢表示，蒐證後發現威加「疑有進口大陸地區苦茶籽混充」，協同嘉義地檢署執行搜索。案件仍在偵查中。',S.pros,'臺北地檢署']];
const unionTimeline=[
['4/4','production','問題批次','中聯製造後來被確認超標的 315 號大豆沙拉油','批號 315-1150404。4/8 至 4/10 陸續出貨給福懋約 588 公噸、福壽約 421 公噸、泰山約 291 公噸，合計約 1,300 公噸。',S.unionFirst,'食藥署 7/1 公告'],
['5/13','warning','第一個明確警訊','南僑自主檢驗取得苯駢芘超標結果','衛福部後續調查確認，南僑在 5/13 已取得超標檢驗結果。這是目前公開時序中最早可確認的異常警訊；但當時沒有通報地方衛生主管機關。',S.unionTrace,'衛福部／食藥署調查'],
['6/10–11','warning','警訊往上游傳','南僑通知福壽，福壽再通知中聯','6/10 南僑把檢驗異狀通知福壽；6/11 福壽通知中聯。也就是說，中聯至少從 6/11 起已接獲問題訊息。',S.unionTrace,'食藥署公布時序'],
['6/15','warning','供應鏈內部知情','中聯召開品保聯繫會議','主管機關後續查核確認，泰山在這場會議已知悉中聯 4/4 製造油品的問題訊息。泰山後來直到 6/30 才向彰化縣衛生局通報。',S.unionPenalty,'彰化縣衛生局調查'],
['6/16、25','testing','中聯複驗','中聯兩度送驗確認','中聯在接獲問題訊息後於 6/16、6/25 送驗；6/29 的報告確認異常。送驗確認可以解釋後續檢驗流程，但不取代食品業者發現產品有危害之虞時的法定通報義務。',S.unionTrace,'食藥署公布時序'],
['6/30','official','官方才接獲通報','中聯傍晚向主管機關通報','食藥署記載 6/30 傍晚接獲中聯通報。從 5/13 第一份已知超標結果算起，相隔 48 天；從中聯 6/11 接獲通知算起，也已過 19 天。',S.unionFirst,'食藥署'],
['7/1','action','政府介入','食藥署會同地方進廠查核、啟動下架回收','官方確認 315-1150404 批大豆沙拉油苯駢芘為 8.1 μg/kg，法定限量 2.0 μg/kg，並公布首波受影響品項及流向。',S.unionFirst,'食藥署'],
['7/7','penalty','延遲通報究責','中聯遭裁罰 1 億 6,520 萬元','衛福部認定中聯延遲通報，且主管機關追查過程發現不實陳述情形，依違規情節與影響程度裁罰。',S.unionTrace,'衛福部／食藥署調查'],
['7/7','penalty','延遲通報＋規避調查','泰山兩項各罰 300 萬元，合計 600 萬元','彰化縣衛生局認定泰山 6/15 已知問題卻未即時通報；7/1 稽查時也未完整說明問題油發現、處理過程及會議資訊，分別裁罰 300 萬元。',S.unionPenalty,'彰化縣衛生局調查'],
['7/7–10','action','風險範圍擴大','又出現其他超標批次，從單批事件升高為製程疑慮','泰山通報中聯 5/12 生產油品相關產品超標；南僑再通報中聯 5/10 製造油品超標。食藥署因此把預防性下架擴至中聯 4–6 月生產的相關油品。',S.unionUpdate,'食藥署 7/12 說明']
];
const app=document.querySelector('#app'); const topbar=()=>`<header class="topbar"><div class="brand"><span>家庭食用油安全專題</span></div><span class="date">資料至 2026.08.06</span></header>`;
function home(){app.innerHTML=`<main class="shell">${topbar()}<section class="hero"><p class="kicker">家庭食用油安全專題</p><h1>家庭食用油<br><span class="issueUnderline">問題批號</span>快查</h1><div class="privacyPromise" aria-label="隱私與使用承諾"><span>不紀錄個資</span><span>免登入</span><span>無需讀取發票載具</span></div></section><section class="branchGrid">${branch('camellia','2026 苦茶油事件','苦茶油事件','比對問題油品，或查看抽驗與追查時序')}${branch('union','2026 中聯油脂事件','中聯油事件','比對受影響商品、日期與批號')}</section><section class="how"><h2>如何使用本網頁</h2><div><b>1</b><p><strong>先選事件</strong><br>中聯油、苦茶油分開整理，不把不同供應鏈混在一起。</p></div><div><b>2</b><p><strong>掃條碼或輸入資料</strong><br>依手上商品的條碼、品名、日期或批號快速比對。</p></div><div><b>3</b><p><strong>最後看官方公告</strong><br>本網站協助快速整理；實際下架、回收範圍仍以主管機關最新公告為準。</p></div></section><section class="externalTopic"><p class="kicker">外部專題參考</p><a href="https://macsire.github.io/bap-report/index.html" target="_blank" rel="noreferrer"><span>苯駢芘與食品安全整理</span><b>前往 BaP Report →</b></a></section><footer class="footer"><span><strong>資料來源</strong>：食藥署、地方政府發布內容，另參考近日媒體。</span><span>v1.3・非政府官方網站</span></footer></main>`}
function branch(key,eyebrow,title,desc){const more=key==='camellia'?`<div class="morePrompt">想了解更多？</div><div class="storyLinks"><a href="#/camellia">事件時序表　→</a><a href="report.html">我們的整理　→</a></div>`:`<a class="storyAction" href="#/union-timeline"><span>想了解更多？點我閱讀！</span><span>→</span></a>`;return `<article class="branch ${key}"><div class="branchHead"><span class="branchDot"></span><div><p>${eyebrow}</p><h2>${title}</h2></div></div><p class="branchDesc">${desc}</p><a class="scanAction" href="#/${key==='union'?'union':'camellia-check'}"><span class="scanIcon">⌗</span><span><b>直接掃條碼比對</b><small>查看手上的油是否在事件名單內</small></span><i>→</i></a>${more}</article>`}
function checker(kind){const isC=kind==='camellia-check',records=isC?camellia:union,event=isC?'苦茶油事件':'中聯油事件',sub=isC?'掃描或輸入手上商品資料，快速比對目前已公開的問題油品。':'掃描條碼或輸入商品資料；依食藥署 2026/07/23 公告清單核對有效日期。';app.innerHTML=`<main class="check ${isC?'camellia':''}"><header class="topbar"><a class="back" href="#/">← 首頁</a><span class="date">資料至 2026.08.06</span></header><section class="checkHero"><p>家庭食用油安全專題</p><h1>${event}</h1><span>${sub}</span></section><section class="panel"><button class="cameraBtn" id="camera">⌗　開啟相機掃條碼<small>對準包裝上的商品條碼</small></button><div class="or">或</div><form id="form"><label>輸入條碼或商品名稱</label><div class="query"><input id="q" placeholder="例如：商品名稱、有效日期"><button>查詢</button></div></form></section><div id="result"></div><section class="help" id="help"><h2>查詢結果怎麼看？</h2><div class="statusList"><span class="status red"><i></i>紅色</span><p>公告列為問題商品或不合格批次，請停止食用並依公告處理。</p><span class="status yellow"><i></i>黃色</span><p>商品可能涉及事件，但仍需再核對日期、批號或公告內容。</p><span class="status green"><i></i>綠色</span><p>在已收錄資料中可明確排除的日期／批次。</p><span class="status white"><i></i>白色</span><p>目前名單沒有相符紀錄；不等於網站替商品背書安全。</p></div></section><footer class="checkFooter">本頁為資料整理工具，實際回收與處置以主管機關最新公告為準。</footer></main>`;document.querySelector('#form').onsubmit=e=>{e.preventDefault();lookup(records,isC)};document.querySelector('#camera').onclick=()=>openCamera(records,isC)}
function norm(s){return String(s||'').toLowerCase().replace(/\s+/g,'')}function lookup(records,isC,val){const q=norm(val??document.querySelector('#q').value);if(!q)return;const hit=records.find(x=>[x.name,x.brand,x.barcode,x.date].some(v=>norm(v).includes(q)));document.querySelector('#help').hidden=true;const box=document.querySelector('#result');if(!hit){box.innerHTML=`<section class="result white"><h2>沒有找到相符紀錄</h2><p>這不代表商品一定安全，也可能是條碼尚未收錄或公告資料未提供條碼。請再核對品名、日期／批號與主管機關最新公告。</p></section>`;return}const cls=hit.dates?'yellow':hit.status;box.innerHTML=`<section class="result ${cls}" id="resultCard"><h2>${hit.brand}｜${hit.name}</h2>${hit.date?`<p><b>有效日期：</b>${hit.date}</p>`:''}${hit.dates?`<label class="dateInput"><b>輸入瓶身有效日期</b><input id="d" maxlength="8" inputmode="numeric" placeholder="例如 20270725"></label>`:''}<p id="note">${hit.note}</p><a href="${hit.source}" target="_blank" rel="noreferrer">查看公告來源 ↗</a></section>`;if(hit.dates)document.querySelector('#d').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,8);if(e.target.value.length===8){const ok=hit.dates.includes(e.target.value),card=document.querySelector('#resultCard');card.className='result '+(ok?'red':'green');document.querySelector('#note').textContent=ok?'這個有效日期符合公告下架範圍，請先停止食用並保留原包裝。':'這個有效日期未列入目前公告的下架日期範圍。'}}}
async function openCamera(records,isC){if(!navigator.mediaDevices?.getUserMedia){alert('這個瀏覽器無法開啟相機，請改用下方輸入欄。');return}const layer=document.createElement('div');layer.className='cameraLayer';layer.innerHTML='<div class="cameraCard"><video playsinline muted></video><p>請將商品條碼放在畫面中央</p><button>關閉相機</button></div>';document.body.append(layer);let stream;const close=()=>{stream?.getTracks().forEach(t=>t.stop());layer.remove()};layer.querySelector('button').onclick=close;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const v=layer.querySelector('video');v.srcObject=stream;await v.play();if(!('BarcodeDetector'in window)){layer.querySelector('p').textContent='這個瀏覽器暫不支援直接辨識條碼，請改用輸入欄。';return}const d=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});const scan=async()=>{if(!document.body.contains(layer))return;try{const c=await d.detect(v);if(c[0]?.rawValue){document.querySelector('#q').value=c[0].rawValue;lookup(records,isC,c[0].rawValue);close();return}}catch{}requestAnimationFrame(scan)};scan()}catch{close();alert('無法開啟相機。請確認相機權限，或直接輸入條碼／品名。')}}
function story(){const events=timeline.map(x=>`<article class="event ${x[1]}"><div class="eventDate">${x[0]}</div><div class="eventCard"><span class="tag">${x[2]}</span><h3>${x[3]}</h3><p>${x[4]}</p><a href="${x[5]}" target="_blank" rel="noreferrer">資料來源｜${x[6]} ↗</a></div></article>`).join('');app.innerHTML=`<main><header class="storyTop"><a class="back" href="#/">← 首頁</a><span class="date">v1.1・資料至 2026.08.06</span></header><section class="storyHero"><p class="kicker">2026 苦茶油事件</p><h1>一瓶超標苦茶油，<br>後來查出了什麼？</h1><p>從 7 月 21 日第一起自主通報開始，把檢驗、下架、供應鏈與司法追查分開看。這不是單一廠商一路擴散的故事。</p></section><section class="note"><h2>小提醒：不檢驗不公告的縣市可能更危險</h2><p>我們把「政府監管行動」和「檢驗出問題」用不同的顏色呈現。誰主動抽驗、誰公開結果，畫面上自然會出現較多紀錄，大家應該鼓勵地方政府主動查驗並公告問題油，而不是把「查得勤」誤讀成「出包多」，打擊有做事的人。</p></section><section class="timelineSection"><div class="sectionHead"><div><p class="kicker">事件時序</p><h2>從通報到擴大追查</h2></div><div class="legend"><span><i class="dot actionDot"></i>監管行動</span><span><i class="dot alertDot"></i>超標／問題商品</span><span><i class="dot traceDot"></i>供應鏈追查</span><span><i class="dot judicialDot"></i>司法偵查</span></div></div><div class="timeline">${events}</div></section><section class="lanes"><h2>目前至少分成三條事件線</h2><div class="laneGrid"><article class="lane"><h3>連淨線</h3><p>連淨自主通報 → 通路下架回收。苦茶籽原料與製程污染來源仍須分開判讀。</p></article><article class="lane"><h3>威加／源春線</h3><p>永豐餘自主通報 → 威加下單 → 源春製油 → 多項產品。8/4 進入刑事偵查。</p></article><article class="lane"><h3>地方擴大抽驗線</h3><p>臺南主動抽驗 → 8/3 驗出另外 3 件超標。目前沒有官方證據可直接併入威加／源春供應鏈。</p></article></div></section><section class="method"><p class="kicker">閱讀原則</p><h2>已證實、業者說法、偵查疑點，分開寫。</h2><p>本頁以食藥署、地方衛生局與檢察機關公開資料為基準。偵查中的「疑似混充」不等同法院已認定；不同地方政府的抽驗量也不能直接拿來當各地風險排名。</p><div class="sources"><a href="${S.start}" target="_blank">食藥署｜連淨案</a><a href="${S.aug}" target="_blank">食藥署｜8/1 調查說明</a><a href="${S.tainan}" target="_blank">臺南市衛生局｜擴大抽驗</a><a href="${S.pros}" target="_blank">臺北地檢署｜8/4 新聞稿</a></div></section><footer class="footer"><span>家庭食用油安全專題・苦茶油事件</span><span>v1.1　更新 2026.08.06</span></footer></main>`}
function unionStory(){const events=unionTimeline.map(x=>`<article class="event ${x[1]}"><div class="eventDate">${x[0]}</div><div class="eventCard"><span class="tag">${x[2]}</span><h3>${x[3]}</h3><p>${x[4]}</p><a href="${x[5]}" target="_blank" rel="noreferrer">資料來源｜${x[6]} ↗</a></div></article>`).join('');app.innerHTML=`<main class="unionStory"><header class="storyTop"><a class="back" href="#/">← 首頁</a><span class="date">v1.3・資料至 2026.08.06</span></header><section class="storyHero"><p class="kicker">2026 中聯油脂事件</p><h1>中聯這桶問題油，<br>為何拖了這麼久才被通報？</h1><p>把「驗出異常」、「供應鏈知情」和「正式通報政府」拆開，時間差就很清楚：5 月中已經出現超標結果，6 月中供應鏈內部已談到問題，主管機關卻到 6 月 30 日才收到正式通報。</p></section><section class="delayBox"><div><strong>5/13</strong><span>第一份已知超標結果</span></div><b>→ 48 天 →</b><div><strong>6/30</strong><span>主管機關接獲通報</span></div></section><section class="note unionNote"><h2>先釐清一件事：股東身分 ≠ 已證明更早知情</h2><p>泰山、福壽、福懋與中聯關係密切，但不能只靠股權關係倒推「5/13 就知道」。目前公開資料可以直接證實的是：福壽 6/10 收到南僑通知、6/11 通知中聯；主管機關並確認泰山在 6/15 的品保聯繫會議已知悉問題。這些才是本頁採用的知情節點。</p></section><section class="timelineSection"><div class="sectionHead"><div><p class="kicker">事件時序</p><h2>警訊怎麼一路卡了 48 天</h2></div><div class="legend"><span><i class="dot warningDot"></i>異常／知情</span><span><i class="dot testingDot"></i>複驗</span><span><i class="dot officialDot"></i>正式通報</span><span><i class="dot actionDot"></i>政府處置</span></div></div><div class="timeline">${events}</div></section><section class="gapSection"><p class="kicker">真正值得追問的空白</p><h2>不是只有 6/29 到 6/30 的一天。</h2><div class="gapGrid"><article><strong>28 天</strong><h3>5/13 → 6/10</h3><p>南僑已取得超標結果，到通知福壽之間隔了約四週。公開資料已確認延遲通報，但目前不足以替這段等待補上一個未證實的理由。</p></article><article><strong>19 天</strong><h3>6/11 → 6/30</h3><p>中聯已接到問題訊息，之後歷經兩次送驗才正式通報。主管機關認定這段過程構成延遲，並對中聯裁罰。</p></article><article><strong>15 天</strong><h3>6/15 → 6/30</h3><p>泰山已在品保聯繫會議知悉問題，卻未立即通報；7/1 接受稽查時又未完整揭露處理過程，最後兩項合計裁罰 600 萬元。</p></article></div></section><section class="method"><p class="kicker">閱讀原則</p><h2>公司的說法，和主管機關查到的事實分開看。</h2><p>本頁以食藥署、地方衛生機關調查與可交叉核對的公開報導為主。企業「自行複驗後才確認」是其處理流程，不等同於主管機關認定可以延後法定通報。</p><div class="sources"><a href="${S.unionFirst}" target="_blank">食藥署｜7/1 首波公告</a><a href="${S.unionUpdate}" target="_blank">食藥署｜7/12 追查進度</a><a href="${S.unionTrace}" target="_blank">中央社｜衛福部完整時序</a><a href="${S.unionPenalty}" target="_blank">中央社｜彰化縣裁罰泰山</a></div></section><footer class="footer"><span>家庭食用油安全專題・中聯油脂事件</span><span>v1.3　更新 2026.08.06</span></footer></main>`}
function polish(){document.querySelectorAll('.back').forEach(a=>a.textContent='家庭食用油安全專題・回到首頁');document.querySelectorAll('.storyTop .date').forEach(el=>el.textContent='v1.3・資料至 2026.08.06');const storyVersion=document.querySelector('.storyTop~section~.footer span:last-child');if(storyVersion)storyVersion.textContent='v1.3　更新 2026.08.06'}
function route(){const p=location.hash.replace(/^#\/?/,'');if(p==='union'||p==='camellia-check')checker(p);else if(p==='camellia')story();else if(p==='union-timeline')unionStory();else home();polish();scrollTo(0,0)}addEventListener('hashchange',route);route();

// v1.32：資料庫更新後的苦茶油查詢與時序資料。
camellia.push(
  {brand:'百年堂',name:'冷壓黃金苦茶油',date:'2028/07/20',batch:'20260720K',status:'red',note:'批號 20260720K；苯駢芘 6.3 μg/kg，已確認不合格，請停止食用並依下架回收資訊處理。'},
  {brand:'鑫隆發',name:'苦茶油（各規格）',date:'2026/1/1–7/31 購買',status:'yellow',note:'業者擴大退貨：該期間購買的所有規格均可退貨退款。這不代表所有批次均檢驗不合格。'},
  {brand:'由豐',name:'將苦茶油（100%）',date:'待確認',status:'yellow',note:'預防性下架／檢驗待確認；不可列為紅色確定問題批號。'}
);
timeline.push(['8/8','action','跨縣市追查・下架','嘉義、臺北、臺中持續追查與下架','百年堂冷壓黃金苦茶油已確認苯駢芘 6.3 μg/kg 不合格、下架回收；由豐將苦茶油（100%）為預防性下架／檢驗待確認。鑫隆發另開放 2026/1/1–7/31 購買的所有規格退貨退款。嘉義、臺北、臺中的行動屬跨縣市追查與下架；目前無官方證據證實這些苦茶油案件與中聯油脂供應鏈有關。',S.tainan,'資料待補官方連結']);
function lookup(records,isC,val){const q=norm(val??document.querySelector('#q').value);if(!q)return;const hit=records.find(x=>[x.name,x.brand,x.barcode,x.date,x.batch].some(v=>norm(v).includes(q)));document.querySelector('#help').hidden=true;const box=document.querySelector('#result');if(!hit){box.innerHTML=`<section class="result white"><h2>沒有找到相符紀錄</h2><p>這不代表商品一定安全，也可能是條碼尚未收錄或公告資料未提供條碼。請再核對品名、日期／批號與主管機關最新公告。</p></section>`;return}const cls=hit.dates?'yellow':hit.status;box.innerHTML=`<section class="result ${cls}" id="resultCard"><h2>${hit.brand}｜${hit.name}</h2>${hit.batch?`<p><b>批號：</b>${hit.batch}</p>`:''}${hit.date?`<p><b>有效日期／範圍：</b>${hit.date}</p>`:''}${hit.dates?`<label class="dateInput"><b>輸入瓶身有效日期</b><input id="d" maxlength="8" inputmode="numeric" placeholder="例如 20270725"></label>`:''}<p id="note">${hit.note}</p>${hit.source?`<a href="${hit.source}" target="_blank" rel="noreferrer">查看公告來源 ↗</a>`:'<p>資料來源連結待補；處置以主管機關最新公告為準。</p>'}</section>`;if(hit.dates)document.querySelector('#d').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,8);if(e.target.value.length===8){const ok=hit.dates.includes(e.target.value),card=document.querySelector('#resultCard');card.className='result '+(ok?'red':'green');document.querySelector('#note').textContent=ok?'這個有效日期符合公告下架範圍，請先停止食用並保留原包裝。':'這個有效日期未列入目前公告的下架日期範圍。'}}}
function polish(){document.querySelectorAll('.back').forEach(a=>a.textContent='家庭食用油安全專題・回到首頁');document.querySelectorAll('.date').forEach(el=>el.textContent=el.closest('.storyTop')?'v1.32・資料至 2026.08.08':'資料至 2026.08.08');if(location.hash==='#/camellia'){const lane=document.querySelector('.lanes .lane:last-child p');if(lane)lane.textContent='臺南主動抽驗 → 8/3 驗出另外 3 件超標，後續由嘉義、臺北、臺中追查與下架。目前沒有官方證據可將這些案件併入威加／源春，或證實與中聯油脂供應鏈有關。';const footer=document.querySelector('.footer span:last-child');if(footer)footer.textContent='v1.32　更新 2026.08.08'}}
route();
// v1.37 全站整合：以最新產品批次資料同步兩條事件線，並在兩個時序頁套用品牌／產品字重。
function rich(text){return String(text).replace(/(泰山|福壽|福懋|中聯油脂|南僑|連淨|永豐餘生技|國際機能食品|威加|源春|聚興製油工廠|德昌商號|宮北合作農場|百年堂|鑫隆發|由豐|庭茂農業生技)/g,'<strong class="brandName">$1</strong>').replace(/(315-1150404 大豆沙拉油|好理調合油|大豆沙拉油|精選蔬菜油|苦茶油|在地金花小菓苦茶油|台灣苦茶油|極品苦茶油|東山苦茶油)/g,'<span class="productName">$1</span>')}
camellia[4]={brand:'庭茂農業生技',name:'極品苦茶油',date:'2028/02/22',status:'red',note:'8/7 官方抽驗確認苯駢芘超標，停止食用並依公告處理。',source:S.aug};
camellia.push({brand:'翰霖貿易',name:'苦茶油',date:'2028/01/21',status:'red',note:'業者自主通報苯駢芘 2.1 μg/kg；列為已確認不合格，依公告處理。',source:S.aug});
function patchSite(){
  document.querySelectorAll('.date').forEach(el=>{if(!el.closest('.reportPage'))el.textContent='資料至 2026.08.09'});
  document.querySelectorAll('.eventCard h3,.eventCard p').forEach(el=>{if(!el.dataset.rich){el.innerHTML=rich(el.textContent);el.dataset.rich='1'}});
  const unionBranch=document.querySelector('.branch.union');
  const camelliaReport=document.querySelector('.branch.camellia a[href="report.html"]');
  if(camelliaReport)camelliaReport.href='camellia-report.html';
  if(unionBranch&&!unionBranch.querySelector('.storyLinks')){const old=unionBranch.querySelector('.storyAction');if(old)old.outerHTML='<div class="morePrompt">想了解更多？</div><div class="storyLinks"><a href="#/union-timeline">事件時序表　→</a><a href="union-report.html">我們的整理　→</a></div>'}
  if(location.hash==='#/camellia'&&!document.querySelector('.camelliaReportLink')){const box=document.querySelector('.method .sources');if(box)box.insertAdjacentHTML('beforeend','<a class="camelliaReportLink" href="camellia-report.html">我們的整理 ↗</a>')}
  if(location.hash==='#/union-timeline'&&!document.querySelector('.unionReportLink')){const box=document.querySelector('.method .sources');if(box)box.insertAdjacentHTML('beforeend','<a class="unionReportLink" href="union-report.html">我們的整理 ↗</a>')}
}
addEventListener('hashchange',()=>setTimeout(patchSite,0));
patchSite();
